### ISSUE TITLE
Can't send to fluentd v1.2 with msgpack

### ISSUE THREAD

**Issue by mashiro** [lestrrat/go-fluent-client#11]
Missing correction?
https://github.com/lestrrat/go-fluent-client/commit/8035b6b31f90b6cf23619eceeb8eb836062a554a#diff-984b621d683cf81bbf404d291c4802a8L104

**Comment by lestrrat** [comment]
むむ？ まだ詳しく見てないですが"missing correction"はどういう意味でしょう？

**Comment by lestrrat** [comment]
あー、subsecondのチェックしてないのか

**Comment by lestrrat** [comment]
should be fixed!

**Comment by mashiro** [comment]
すみません指摘が曖昧すぎました。
修正ありがとうございます！
